[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/movies.json"
  to = "/movies"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 304
  force = true