# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# [[redirects]]
#   from = "/api/movies"
#   to = "/api/movies.json"

# [[redirects]]
#   from = "/api"
#   to = "/index.html"
